import React from 'react'

const Assessment1Instruction = () => {
  return (
    <div>
      <div class="card">
                <div class="card-header">
                    <h3>Assessment 1: <small>Javascript / Vue.js</small></h3>
                </div>
                <div class="card-body">
                    <h4 class="text-primary">Setup and Information</h4>
                      <p class="text-primary">The list group in the right column is generated by the vue.js framework. All the data and methods are contained in the assess_module.js file. The HTML template is located in the assessment1func method of the class.assess_module.php file. Familiarize yourself with these files then complete the following tasks.</p>

                      <p class="text-primary">Reference the documentation at vuejs.org for information. Specifically the Conditionals and Loops section.</p>

                      <h3>Your Tasks</h3>
                      <p>Modify the template to display the price and length of each widget in the list.</p>

                      <p>Add bootstrap badge pill objects to display all the tag codes for each of the widgets. See the (XX) static examples.</p>

                      <p>Create a legend or key for the various tags below the widget list.</p>

                      <p>Use "v-if" in vue.js to filter out widgets who's length is below the filter input number so they don't display in the list.</p>
                      </div>
                      </div>
    </div>
  )
}

export default Assessment1Instruction
